import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login';
import { unstable_getServerSession } from "next-auth/next"
import { authOptions } from './api/auth/[...nextauth]'
import { useSession } from "next-auth/react"
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { db } from '../firebase';

export default function Home() {
  const { data: session, status, posts } = useSession()

  if (!session || status === "unauthenticated") return <Login />
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className='flex'>
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  )
}

export async function getServerSideProps({ req, res }) {

  const posts = await db.collection('posts').orderBy("timestamp", "desc").get();
  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null

  }))

  return {
    props: {
      session: await unstable_getServerSession(req, res, authOptions),
      posts: docs
    }
  }
}